### ISSUE TITLE
Remove evtest dependency

### ISSUE THREAD

**Issue by mqudsi** [mqudsi/syngesture#1]
As part of the initial proof-of-concept, I opted into using `evtest` (directly installable at least on Debian/Ubuntu/etc via `apt install evtest`) to read the input events coming out of the touchpad's `libevdev` device and parse the output.

In the name of reducing dependencies and minimizing friction for adoption, we should switch to directly opening the touchpad `/dev/whatever` device node and reading the input events directly rather than spawning an `evtest` instance and parsing the results. This would presumably additionally bring down the already virtually nil CPU usage by removing the regex matching that takes place when a gesture is in progress.

**Comment by iamkroot** [comment]
I would recommend using the excellent [`evdev-rs`](https://crates.io/crates/evdev_rs) crate for this purpose. It is a high level wrapper over `libevdev` and hence allows for _slightly_ more robustness over reading `/dev/inputX` directly. It also comes with all the enums pre-defined.

I have used it recently for a personal project at https://github.com/iamkroot/asus-numpad. See particularly https://github.com/iamkroot/asus-numpad/blob/b66e77890c24ddd66e18bb7c95f0b01023426a08/src/main.rs#L311-L434. Your use case is very similar to mine, so it should be easy to translate to this repo.

**Comment by mqudsi** [comment]
Thanks, @iamkroot - that does indeed look like it would work great for our needs.

**Comment by mqudsi** [comment]
Just an update: I removed the evtest dependency and am now using the crate you mentioned, @iamkroot. 

Not using evtest drastically improves battery life by reducing the interrupts on the associated SPI/I2C IRQ. The latest master is now evtest-free, all that remains is to release v2. 

One thing that is uglier is that you can’t just set the suid bit on evtest to avoid needing sudo. Instead you need to make sure the uvdev rules set up a group that has permission to access the device and add yourself to the group. That part sucks.

**Comment by mqudsi** [comment]
It seems sane distros add the default user to the `input` group that can open and listen for events against these devices, but Ubuntu (which is kinda popular) doesn't.

**Comment by smileBeda** [comment]
I use v1.0.1 of this repo and whever triggering `syngestures` I get:
`evtest: no such file or folder`.

It does nonetheless work somewhat, but not reliably: it kind of falls asleep randomly, after a reboot it won't work even if it is added as a startup item, and often needs to be "woken up" by hitting the clickpad with a bunch of clicks and swipes, suddenly it comes back.

I am pretty sure the issues I see are due to the warning, but ... A) as I understand there should not be a dependindecy on it? and B) I have evtest installed anyway (arch extra package).

I also kinda miss any commit around march 2023 (where you mention to have removed evtest) so I am not even sure if this ever was added to the codebase?
Even `master` still downloads `Downloaded evdev-rs v0.6.1...Downloaded evdev-sys v0.2.5`

**Comment by mqudsi** [comment]
@smileBeda you can try the beta release from this post: https://github.com/mqudsi/syngesture/issues/11#issuecomment-1554792538

**Comment by smileBeda** [comment]
OK this works. However it seems to have been built with `--features logging` on. Is the tar.zip you sent the exact same as `master``? I can then just download master and rebuild without logging... otherwise the zip would need to be rebuilt without logging, since we cannnot turn it off as the package is already compiled.

**Comment by arrowd** [comment]
I bumped into this issue when found that `syngesture` does not terminate `evtest` process when receiving SIGINT.

Is there any ETA on a release containing the evtest dependency removal?

**Comment by mqudsi** [comment]
I should probably make a release, there haven’t been any issues reported with the new approach!

**Comment by mqudsi** [comment]
It's now admittedly four years later from when this issue was opened, but I've just released Syngestures 2.0 with the promised changes (though they've been available in the repo for years).

Release notes and download link: https://github.com/mqudsi/syngesture/releases/tag/2.0.0
